SELECT VERSION();

USE CRYPTOWORLD;

CREATE OR REPLACE TRIGGER TRIG_BEFORE_INSERT_CRYPTO
BEFORE INSERT ON CryptoCoins
REFERENCING NEW AS N
FOR EACH ROW
WHEN (N.Price < 0)
    SIGNAL SQLSTATE '75999' ('Crypto price can not be negative number');

CREATE OR REPLACE TRIGGER TRIG_BEFORE_INSERT_TRANS
BEFORE INSERT ON Transactions
REFERENCING NEW AS N
FOR EACH ROW
WHEN (N.Amount < 0)
    SIGNAL SQLSTATE '75999' ('Amount can not be lesser than zero');

CREATE OR REPLACE TRIGGER TRIG_BEFORE_INSERT_BOOKS
BEFORE INSERT ON Users
REFERENCING NEW AS U
FOR EACH ROW
WHEN (U.Username IN (SELECT Username FROM Users))
    SIGNAL SQLSTATE '75999' ('Username already taken');


INSERT INTO Books(Id, Name, YEAROFPUBLICATION) VALUES (default, 'Harry Potter', 1997); --commented

INSERT INTO Authors(ALIAS, FIRSTNAME, SECONDNAME, BIRTHDATE, YEAROFFIRSTPUBLISHEDBOOK, YEAROFLASTPUBLISHEDBOOK) --cpommented
VALUES ('Unknown', 'Unknown', 'Unknown', 2000, 2000, 2050);
